version: "3"

services:
    digital-api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: digital-api
        env_file: .env
        ports:
            - "5600:5600"
        volumes:
            - ./src:/app/src
        networks:
            - digital-common-dev
        command: yarn dev

networks:
    digital-common-dev:
        external: true
